# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

tone_instructions: Prefer concise responses (high information density, low fluff)
inheritance: true

reviews:
  profile: quiet
  request_changes_workflow: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  auto_apply_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false

  high_level_summary: true
  high_level_summary_instructions: "Give a brief description of the changes in 50 words or less."
  high_level_summary_in_walkthrough: false

  auto_review:
    auto_incremental_review: true
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false


knowledge_base:
  automatic_repository_linking: true
  issues:
    scope: local
  pull_requests:
    scope: local
